version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: quiz-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: quiz_game_db

    volumes:
      - db-data:/var/lib/mysql
      - ./db_charlotte.sql:/docker-entrypoint-initdb.d/db_charlotte.sql

volumes:
  db-data: